name: Build cmd

on:
  # Should only be used by other workflows
  workflow_call:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: Build cmd
        id: build-cmd
        run: go build cmd
