name: Lint

on:
  # Should only be used by other workflows
  workflow_call:

permissions:
  contents: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          # use the default if on main branch, otherwise use the pull request config
          args: --timeout=30m --config=.golangci.yml
          only-new-issues: true
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true
