name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release, eg. v0.0.1'
        required: true

permissions:
  contents: write

jobs:
  run-unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/test.yaml

  lint:
    name: Lint
    uses: ./.github/workflows/lint-go.yaml
