name: Unit Tests

on:
  # Should only be used by other workflows
  workflow_call:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make git build-essential    

      - name: Pull Docker Image
        run: docker pull vechain/thor:latest
        
      - name: Make Test
        id: unit-test
        run: go test ./... -count=1
