name: Test Custom Action

on:
  #push to any branch
  push:
    branches:
      - '*'

jobs:
  test-action:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install action
        uses: vechain/networkhub@add-release-step-2
        with:
          version: 'v0.0.3'
          token: ${{ secrets.GITHUB_TOKEN }}

