name: Unit Tests

on:
  # Should only be used by other workflows
  workflow_call:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make git build-essential
      
      - name: Set vechain/thor reference
        id: set-ref
        run: |
          # Default fallback commit
          REF="master"
          
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            # For pull_request events, we only look at the PR's base branch
            if [[ "$GITHUB_BASE_REF" == release/* ]]; then
              REF="$GITHUB_BASE_REF"
            fi
          fi

          echo "ref=$REF" >> "$GITHUB_OUTPUT"

      - name: Make Test
        id: unit-test
        env:
          THOR_BRANCH: ${{ steps.set-ref.outputs.ref }}
        run: go test ./... -v -count=1
